# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15693e95759ff1a1e5dca8db7670bba9a700a92e160bca928d59a3d099a38db9a106e0401a552cb97a023716063438d29345b013fc7081834d477768d7b8e515

test:
  secret_key_base: adec3302614c0cad60ef341262f592d0b85dfda85b8ea58e1a592cb427dbce1c8dbac61f3f4a47cec09f914e1ae27bbcc3ee796fb70956cbbd01814e7b4b0db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
